# Generated by Django 5.2.4 on 2026-04-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Yil'),
        ),
        migrations.AddField(
            model_name='group',
            name='month',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'Yanvar'), (2, 'Fevral'), (3, 'Mart'), (4, 'Aprel'),
                         (5, 'May'), (6, 'Iyun'), (7, 'Iyul'), (8, 'Avgust'),
                         (9, 'Sentabr'), (10, 'Oktabr'), (11, 'Noyabr'), (12, 'Dekabr')],
                verbose_name='Oy'
            ),
        ),
    ]
