# Generated by Django 5.2.4 on 2026-04-02 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_add_year_month_to_group'),
        ('superadmin', '0006_alter_administrator_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Yo'nalish nomi")),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='superadmin.filial', verbose_name='Filial')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='superadmin.organization', verbose_name='Tashkilot')),
            ],
            options={
                'verbose_name': "Yo'nalish",
                'verbose_name_plural': "Yo'nalishlar",
            },
        ),
        migrations.AddField(
            model_name='group',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='students.direction', verbose_name="Yo'nalish"),
        ),
    ]
