# Generated by Django 5.2.4 on 2026-04-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_direction_group_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='plain_password',
            field=models.CharField(blank=True, help_text="Tizimga kirish paroli (ochiq ko'rinishda)", max_length=20, null=True),
        ),
    ]
