# Generated by Django 5.2.4 on 2026-04-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_grouplesson_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='early_leave_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
