# Generated by Django 5.2.4 on 2026-06-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_add_is_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_muqobil',
            field=models.BooleanField(default=False, verbose_name='Muqobil malaka oshirishda'),
        ),
        migrations.AddField(
            model_name='student',
            name='muqobil_from',
            field=models.DateField(blank=True, null=True, verbose_name="Muqobilga o'tgan sana"),
        ),
    ]
