# Generated by Django 5.2.4 on 2026-08-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_group_limit_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='lms_group_code',
            field=models.UUIDField(blank=True, db_index=True, help_text="LMS (SportEdu Jadval) dagi Group.external_code — import orqali to'ladi", null=True, unique=True, verbose_name='LMS guruh kodi'),
        ),
        migrations.AddField(
            model_name='group',
            name='lms_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi import'),
        ),
    ]
