# Generated by Django 5.2.4 on 2026-08-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_group_lms_group_code_group_lms_synced_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='smena',
            name='lms_shift_code',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True, verbose_name='LMS smena kodi'),
        ),
    ]
