from django.urls import path
from apps.home import views

urlpatterns = [

    path('', views.index, name='home'),
    # path('administrators/', views.admins, name='admins'),
    # path('administrators_create/', views.admin_create, name='administrators_create'),
    # path('administrators/<int:pk>', views.admin_detail, name='admin_update'),
    # path('admin_delete/<int:pk>', views.AdminDelete.as_view(), name='admin_delete'),
    path('employees/', views.employees, name='employees'),
    path('employees_create/', views.employee_create, name='employees_create'),
    path('employees/<int:pk>', views.employee_detail, name='employee_update'),
    path('employee_delete/<int:pk>', views.EmployeeDelete.as_view(), name='employee_delete'),
    # Jadval shablonlari (yangi)
    path('schedules/', views.schedules, name='schedules'),
    path('schedules/create/', views.schedule_create, name='schedule_create'),
    path('schedules/<int:pk>/', views.schedule_detail, name='schedule_detail'),
    path('schedules/<int:pk>/delete/', views.ScheduleDelete.as_view(), name='schedule_delete'),
    path('report/', views.get_report_date, name='home_get_dates'),
    path('report/monthly/', views.monthly_summary, name='monthly_summary'),
    path('report/download/', views.download_excel, name='report_download'),
    path('report/download-all/', views.report_download_excel, name='report_download_all'),
    path('employees/<int:pk>/report/', views.employee_report, name='employee_report'),
    path('employees/<int:pk>/report/download', views.employee_download_excel, name='employee_download_excel'),
    path('salaries/', views.salary_list, name='salary_list'),
    path('salaries/<int:pk>/update/', views.salary_update, name='salary_update'),

    # Monitoring bo'limi
    path('monitoring/', views.monitoring_dashboard, name='monitoring_dashboard'),
    path('monitoring/reports/', views.monitoring_reports, name='monitoring_reports'),
    path('monitoring/limit/', views.monitoring_limit_settings, name='monitoring_limit_settings'),
    path('monitoring/exceeded/', views.monitoring_exceeded, name='monitoring_exceeded'),

    # path('users/', views.users_view, name='users'),
    # path('categories/', views.categories, name='home_categories'),
    # path('categories/<int:pk>', views.category_detail, name='category_update'),
    # path('subcategories/', views.sub_categories, name='home_subcategories'),
    # path('subcategories/<int:pk>', views.subcategory_detail, name='subcategory_update'),
    # path('manufacturers/', views.manufacturers, name='home_manufacturers'),
    # path('manufacturers/<int:pk>', views.manufacturer_detail, name='manufacturer_update'),
    # path('cashback/<int:pk>', views.cashback_detail, name='cashback_update'),
    # path('products/', views.products, name='home_products'),
    # path('products/<int:pk>', views.product_detail, name='product_update'),
    # path('cashbacks_by_cashback/<int:pk>', views.user_cashback_by_cashback, name='cashbacks_by_cashback'),
    # path('notifications/', views.notifications_list, name='home_notifications'),
    # path('notification_create/', views.notification_create, name='notifications_create'),
    # path('notification/<int:pk>/', views.notification_detail, name='notifications_detail'),
    # path('notification_delete/<int:pk>/', views.NotificationDelete.as_view(), name='notifications_delete'),
    # path('sales/', views.sales, name='home_sales'),
    # path('sales_create/', views.sale_create, name='sale_create'),
    # path('sales_detail/<int:pk>', views.sale_detail, name='sale_detail'),
    # path('sales_delete/<int:pk>', views.SaleDelete.as_view(), name='sale_delete'),
    # path('story_categories/', views.story_categories, name='home_story_category'),
    # path('story_category_create/', views.story_category_create, name='story_category_create'),
    # path('story_category_delete/<int:pk>', views.StoryCategoryDelete.as_view(), name='story_category_delete'),
    # path('stories/', views.stories, name='home_stories'),
    # path('story_delete/<int:pk>', views.StoryDelete.as_view(), name='story_delete'),
    # path('story_create/', views.story_create, name='story_create'),

]
