# Generated by Django 5.2.4 on 2026-03-13 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_organization_administrator_is_org_admin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={'verbose_name': 'Administrator', 'verbose_name_plural': 'Administratorlar'},
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='is_org_admin',
        ),
        migrations.AddField(
            model_name='administrator',
            name='role',
            field=models.CharField(choices=[('org_admin', 'Tashkilot Superadmini'), ('filial_admin', 'Filial Admini'), ('hr_admin', "Xodimlar Bo'limi"), ('edu_admin', "O'quv Bo'limi"), ('monitoring', "Monitoring Bo'limi")], default='hr_admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buildings', to='superadmin.filial')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='superadmin.organization')),
            ],
            options={
                'verbose_name': "O'quv korpus",
                'verbose_name_plural': "O'quv korpuslar",
            },
        ),
    ]
