# Generated by Django 5.2.4 on 2026-08-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_alter_administrator_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('key_prefix', models.CharField(db_index=True, max_length=12, unique=True)),
                ('key_hash', models.CharField(max_length=64)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('allowed_ips', models.JSONField(blank=True, default=list, help_text='Bo\'sh bo\'lsa — IP cheklovi yo\'q. Masalan: ["195.158.30.179"]')),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Integratsiya kaliti',
                'verbose_name_plural': 'Integratsiya kalitlari',
            },
        ),
    ]
