# Generated by Django 5.2.4 on 2026-03-13 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_location_organization'),
        ('superadmin', '0006_alter_administrator_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Kirish Chiqish', 'verbose_name_plural': 'Kirish Chiqishlar'},
        ),
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Telegram Foydalanuvchi', 'verbose_name_plural': 'Telegram Foydalanuvchilar'},
        ),
        migrations.AlterModelOptions(
            name='workschedule',
            options={'verbose_name': 'Ish jadvali', 'verbose_name_plural': 'Ish jadvallari'},
        ),
        migrations.AddField(
            model_name='attendance',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='main.location'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('employee', 'Xodim'), ('teacher', "O'qituvchi")], default='employee', max_length=20),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_schedules', to='main.location'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date', 'location')},
        ),
        migrations.CreateModel(
            name='ExtraSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_schedules', to='main.employee')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_schedules', to='main.location')),
                ('weekday', models.ManyToManyField(related_name='extra_schedules', to='superadmin.weekday')),
            ],
            options={
                'verbose_name': "Qo'shimcha jadval",
                'verbose_name_plural': "Qo'shimcha jadvallar",
            },
        ),
        migrations.CreateModel(
            name='SalaryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_hours', models.FloatField(default=168, help_text="Oyda ishlashi kerak bo'lgan soat soni (masalan 168)")),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0, help_text="Oylik oklad (so'm)", max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_config', to='main.employee')),
            ],
            options={
                'verbose_name': 'Maosh konfiguratsiyasi',
                'verbose_name_plural': 'Maosh konfiguratsiyalari',
            },
        ),
    ]
