# Generated by Django 5.2.4 on 2026-03-14 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_attendance_options_alter_telegramuser_options_and_more'),
        ('superadmin', '0006_alter_administrator_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workschedule',
            options={'verbose_name': 'Ish jadvali (eski)', 'verbose_name_plural': 'Ish jadvallari (eski)'},
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Jadval nomi')),
                ('start', models.TimeField(verbose_name='Kelish vaqti')),
                ('end', models.TimeField(verbose_name='Ketish vaqti')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='superadmin.filial', verbose_name='Filial')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='main.location', verbose_name='Lokatsiya')),
                ('weekdays', models.ManyToManyField(related_name='schedules', to='superadmin.weekday', verbose_name='Hafta kunlari')),
            ],
            options={
                'verbose_name': 'Jadval',
                'verbose_name_plural': 'Jadvallar',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='schedules',
            field=models.ManyToManyField(blank=True, related_name='employees', to='main.schedule', verbose_name='Jadvallar'),
        ),
    ]
