# Generated by Django 5.2.4 on 2026-03-14 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_add_schedule_model_and_employee_schedules'),
        ('superadmin', '0006_alter_administrator_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='end',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='weekdays',
        ),
        migrations.CreateModel(
            name='ScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(verbose_name='Kelish vaqti')),
                ('end', models.TimeField(verbose_name='Ketish vaqti')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='main.schedule', verbose_name='Jadval')),
                ('weekday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_days', to='superadmin.weekday', verbose_name='Hafta kuni')),
            ],
            options={
                'verbose_name': 'Jadval kuni',
                'verbose_name_plural': 'Jadval kunlari',
                'unique_together': {('schedule', 'weekday')},
            },
        ),
    ]
