# Generated by Django 5.2.4 on 2026-03-14 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_add_scheduleday_remove_schedule_weekdays_times'),
        ('superadmin', '0006_alter_administrator_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_users', to='superadmin.organization', verbose_name='Tashkilot (referal orqali)'),
        ),
    ]
