# Generated by Django 5.2.4 on 2026-03-14 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_telegramuser_organization'),
        ('superadmin', '0006_alter_administrator_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='organization',
        ),
        migrations.CreateModel(
            name='InviteToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_tokens', to='superadmin.filial', verbose_name='Filial')),
            ],
            options={
                'verbose_name': 'Taklif havolasi',
                'verbose_name_plural': 'Taklif havolalari',
            },
        ),
    ]
