# Generated by Django 5.2.4 on 2026-03-16 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_telegramuser_organization_invitetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration_minutes', models.IntegerField(default=0)),
                ('record_type', models.CharField(choices=[('late', 'Kechikish'), ('early_leave', 'Erta ketish'), ('overtime', 'Ortiqcha ishlash')], max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='main.employee')),
            ],
            options={
                'verbose_name': 'Kunlik davomot xulosasi',
                'verbose_name_plural': 'Kunlik davomot xulosalari',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date', 'record_type')},
            },
        ),
    ]
