# Generated by Django 5.2.4 on 2026-08-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_attendanceevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lms_building_code',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True, verbose_name='LMS bino kodi'),
        ),
    ]
